spring:
  application:
    name: eureka-service

server:
  port: 8080

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka
  instance:
    prefer-ip-address: true

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    project:
      path: /project/**
      serviceId: PROJECT-SERVICE
