zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  #Uncomment to disable auto-registering all services read from Eureka
  ignoredServices: '*'
  routes:
    users:
      path: /**
      url: http://localhost:8090
